accounts/urls.py
from django.urls import path
from .views import login_view, logout_view, signup_view

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup_view, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


def home_redirect(request):
    return redirect("home")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", home_redirect),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path
from .views import ReceiptListView, create_receipt
from .views import (
    ReceiptListView,
    category_list,
    account_list,
    create_category,
    create_account_view,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("<int:purchaser>/", ReceiptListView.as_view(), name="receipt_list"),
    path("create/", create_receipt, name="create_receipt"),
    path("categories/", category_list, name="category_list"),
    path("categories/create/", create_category, name="create_category"),
    path("accounts/", account_list, name="account_list"),
    path("accounts/create/", create_account_view, name="create_account"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

receipts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        User, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        User, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        User, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        ExpenseCategory, related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        Account,
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return f"{self.vendor} - {self.total}"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)
    password_confirmation = forms.CharField(
        max_length=150, widget=forms.PasswordInput
    )

receipts/forms.py
from django import forms
from .models import Receipt, ExpenseCategory, Account


class ReceiptForm(forms.ModelForm):
    class Meta:
        model = Receipt
        fields = ["vendor", "total", "tax", "date", "category", "account"]


class ExpenseCategoryForm(forms.ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = ["name"]


class CreateAccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ["name", "number"]

    def __init__(self, *args, **kwargs):
        self.owner = kwargs.pop("owner", None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        account = super().save(commit=False)
        account.owner = self.owner
        if commit:
            account.save()
        return account

accounts/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from .forms import LoginForm, SignUpForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.db.utils import IntegrityError


def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")
            else:
                form.add_error(None, "Invalid username or password")
    else:
        form = LoginForm()
    return render(request, "accounts/login.html", {"form": form})


def logout_view(request):
    logout(request)
    return redirect("login")


def signup_view(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]
            if password == password_confirmation:
                try:
                    user = User.objects.create_user(
                        username=username, password=password
                    )
                    login(request, user)
                    return redirect("home")
                except IntegrityError:
                    messages.error(request, "This username is already taken.")
                    raise
            else:
                messages.error(request, "The passwords do not match.")
    else:
        form = SignUpForm()

    return render(request, "accounts/signup.html", {"form": form})

receipts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ReceiptForm, ExpenseCategoryForm, CreateAccountForm
from .models import Receipt, ExpenseCategory, Account
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.list import ListView


# class ReceiptListView(ListView):
#   model = Receipt
#   context_object_name = "receipts"
#   template_name = "receipts/list.html"


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"
    context_object_name = "receipts"
    ordering = ["-date"]
    paginate_by = 10

    def get_queryset(self):
        return super().get_queryset().filter(purchaser=self.request.user)


@login_required
def create_receipt(request):
    if request.method == "POST":
        form = ReceiptForm(request.POST)
        if form.is_valid():
            receipt = form.save(commit=False)
            receipt.purchaser = request.user
            receipt.save()
            return redirect("home")
    else:
        form = ReceiptForm()
    return render(request, "receipts/create_receipt.html", {"form": form})


@login_required
def category_list(request):
    categories = ExpenseCategory.objects.filter(owner=request.user)
    context = {"categories": categories}
    return render(request, "receipts/category_list.html", context)


@login_required
def account_list(request):
    accounts = Account.objects.filter(owner=request.user)
    context = {"accounts": accounts}
    return render(request, "receipts/account_list.html", context)


@login_required
def create_category(request):
    if request.method == "POST":
        form = ExpenseCategoryForm(request.POST)
        if form.is_valid():
            expense_category = form.save(commit=False)
            expense_category.owner = request.user
            expense_category.save()
            return redirect("category_list")
    else:
        form = ExpenseCategoryForm()
    return render(request, "receipts/create_category.html", {"form": form})


@login_required
def create_account_view(request):
    if request.method == "POST":
        form = CreateAccountForm(request.POST, owner=request.user)
        if form.is_valid():
            form.save()
            return redirect("account_list")
    else:
        form = CreateAccountForm(owner=request.user)
    return render(request, "receipts/create_account.html", {"form": form})

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
      <h1>Login</h1>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
      </form>
    </div>
  </main>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Signup</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Signup</button>
        </form>
    </div>
</main>
{% endblock %}

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %}{% endblock %}
</body>
</html>

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'receipt_list' %}">Receipts</a></li>
                <li><a href="{% url 'create_receipt' %}">New Receipt</a></li>
                <li><a href="{% url 'category_list' %}">Expense Categories</a></li>
                <li><a href="{% url 'create_category' %}">New Expense Category</a></li>
                <li><a href="{% url 'account_list' %}">Accounts</a></li>
                <li><a href="{% url 'create_account' %}">New Account</a></li>
                <li><a href="{% url 'logout' %}">Log Out</a></li>
                {% else %}
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %}{% endblock %}
</body>
</html>

receipts/templates/receipts/account_list.html
{% extends "base.html" %}

{% block content %}
<main>
    <h1>Accounts</h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Number of receipts</th>
            </tr>
        </thead>
        <tbody>
            {% for account in accounts %}
                <tr>
                    <td>{{ account.name }}</td>
                    <td>{{ account.number }}</td>
                    <td>{{ account.receipt_set.count }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3">No accounts found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'create_account' %}">New Account</a>
</main>
{% endblock %}

receipts/templates/receipts/category_list.html
{% extends "base.html" %}

{% block content %}
<main>
    <h1>Expense Categories</h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number of receipts</th>
            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
                <tr>
                    <td>{{ category.name }}</td>
                    <td>{{ category.receipt_set.count }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="2">No categories found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'create_category' %}">New Expense Category</a>
</main>
{% endblock %}

receipts/templates/receipts/create_account.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div>
      <h1>Create Account</h1>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
      </form>
    </div>
  </main>
{% endblock %}

receipts/templates/receipts/create_category.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Create Category</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
</main>
{% endblock %}

receipts/templates/receipts/create_receipt.html
{% extends 'base.html' %}

{% block content %}
<main>
  <div>
    <h1>Create Receipt</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
</main>
{% endblock %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <h1>My Receipts</h1>
    <table>
      <thead>
        <tr>
          <th>Vendor</th>
          <th>Total</th>
          <th>Tax</th>
          <th>Date</th>
          <th>Category</th>
          <th>Account</th>
        </tr>
      </thead>
      <tbody>
        {% for receipt in receipts %}
          <tr>
            <td>{{ receipt.vendor }}</td>
            <td>{{ receipt.total }}</td>
            <td>{{ receipt.tax }}</td>
            <td>{{ receipt.date|date:"m/d/y" }}</td>
            <td>{{ receipt.category.name }}</td>
            <td>{{ receipt.account.name }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'create_receipt' %}">New Receipt</a>
  </main>
{% endblock %}